--- # FULL INCLUDE TASKS EXAMPLE
- hosts: local
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:  
    - include: plays/packages.yaml
    - name: verify the telnet package is installed
      raw: yum list installed | grep telnet > /home/ansible/pkgs.log
