--- # Myfirstplaybook
- hosts: apacheserver
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no 
  vars: 
    playbook_version: 0.1b
  vars_files: 
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
      prompt: web domain
  tasks:
    - name: Install lynx web broqser
      action: apt name=lynx state=present
    - name: check for telnet client
      action: apt name=telnet state=absent
