--- # Myfirstplaybook
- hosts: apacheserver
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no 
  vars: 
    playbook_version: 0.1b
  vars_files: 
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
      prompt: web domain
  tasks:
    - name: Install apache2 webserver
      action: apt name=apache2 state=installed
      notify: start apache2
  handlers:
    - name: start apache2
      action: service name=apache2 state=restarted 



