--- # my first playbook for ansible
- hosts: local
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yaml
    - conf/webdefaults.yaml
  vars_prompt:
    - name: web_domain
      prompt: web domain
  tasks:
    - name: Install Apache webserver
      action: yum name=httpd state=installed
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted  
