--- # my first playbook for ansible
- hosts: local
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yaml
    - conf/webdefaults.yaml
  vars_prompt:
    - name: web_domain
      prompt: web domain
  tasks:
    - name: install lynx web browser
      action: yum name=lynx state=installed
    - name: check for telnet client
      action: yum name=telnet state=absent
