--- # The Pause Module
- hosts: local
  sudo: yes
  gather_facts: no
  connection: ssh
  tasks:
   - name: Install httpd
     action: yum name=httpd state=installed
   - name: pausing 
     pause: 
        prompt: 'Make sure the installation is complete...'
   - name: verify lynx installation is complete
     action: yum name=lynx state=present
     
