--- # Raw Module Example
- hosts: local
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: find the system uptime for the host above
      raw: /usr/bin/uptime > uptimes.log

