--- # outline to playbook translation
- hosts: apacheserver
  user: ansible
  sudo: yes
  gather_facts: no
  tasks: 
  - name: date/time starts
    raw: /bin/date > /home/ansible/playbook_start.log
  - name: install apache server
    apt: name=apache2 state=latest
  - name: starting web service
    service: name=apache2 state=started
  - name: verify tha the web service is running
    command: systemctl status apache2
    register: result
  - debug: var=result
  - name: install client software
    apt: pkg=telnet state=latest
  - name: install clinet software
    apt: pkg=lynx state=latest
  - name: log all packages installed on the system
    raw: apt list installed > /home/ansible/installed.log
  - name: date/time ends
    raw: /bin/date > /home/ansible/playbook_end.log
