- name: restart HTTPD 
  service: name={{ redhat_apache }} state=restarted
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes
- name: restart HTTPD
  service: name={{ debian_apache }} state=restarted
  when: "asnible_os_family == 'Debian'"
  ignore_errors: yes
- name: Installtelnet
  yum: pkg=telnet state=latest
